### ISSUE TITLE
Episode 5 - Image Deleting Logic

### ISSUE THREAD

**Issue by kingdomac** [themsaid/ergodnc#10]
When you delete an image you validate if the image is either the only one or the only one and featured if so you are not allowing to delete it, but at the same time, you are allowing to create an office without a featured image or a normal image.

So I consider the logic above as a paradox because if you want to apply these rules on the delete image action you should also make the featured image in the create & update office as a required field in the user request. 

The best scenario is to make the featured image a field in the Offices table and by that, you will skip the multiple queries on the images table just for adding a feature one.

**Comment by themsaid** [comment]
When you create an office, it's going to be pending approval. So it won't be available for the public right away, and just no need to ask for a featured image at this point.
