### ISSUE TITLE
Episode 4 - Notification Logic

### ISSUE THREAD

**Issue by kingdomac** [themsaid/ergodnc#11]
When creating or updating an office, you are attaching or sync the tags in the database inside the transaction function, then you are sending notification to the admin outside the transaction, but if it was committed or failed you are in both situations sending the notification which is wrong, you need to use the "Manually using transactions" concept to control the transaction status.

**Comment by themsaid** [comment]
If the transaction fails, an exception will be thrown and the notification won't be sent.
