### ISSUE TITLE
  Call to undefined method Tests\Feature\OfficeImageControllerTest::assertModelMissing()

### ISSUE THREAD

**Issue by gul-ahmad** [themsaid/ergodnc#12]
what I am missing here

**Comment by kingdomac** [comment]
Show us the code of the test controller, and the artisan command that you are using

**Comment by aarbi** [comment]
That method was added in Laravel 8.61.0. Just make sure that you have the correct version in the composer.lock file

**Comment by themsaid** [comment]
you need to upgrade your laravel app
