### ISSUE TITLE
Upload image

### ISSUE THREAD

**Issue by kingdomac** [themsaid/ergodnc#13]
In the OfficeImageController/store function, it returns an error when uploading the image via postman "Call to a member function storePublicly() on null" it cannot read the image file posted!! But the test passed successfully!!

**Comment by dagrv** [comment]
Have you tried with another client (with Insomnia let us say) ? And you filled correctly the Accept input ?

**Comment by kingdomac** [comment]
No, I'm using the postman and yes the  Accept and content-type are correctly filled.

**Comment by dagrv** [comment]
Can we see your code ?

**Comment by kingdomac** [comment]
<?php

namespace App\Http\Controllers;

use App\Http\Resources\ImageResource;
use App\Models\Office;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class OfficeImageController extends Controller
{
    public function store(Office $office)
    {
        request()->validate([
            'image' => ['file', 'max:5000', 'mimes:png,jpg']
        ]);
        return response()->json(['f' => request()->file('image')]);
        $path = request()->file('image')->storePublicly('/', ['disk' => 'public']);

        $image = $office->images()->create([
            'path' => $path
        ]);

        return ImageResource::make($image);
    }
}

**Comment by kingdomac** [comment]
![scr1](https://user-images.githubusercontent.com/6049755/134706138-9389e1ef-36cf-4352-9fe9-233b4a96ec35.jpg)

**Comment by kingdomac** [comment]
i even tried to send a text input request under "test' and read it via request('test') it also returns null

**Comment by kingdomac** [comment]
I figured out, the issue was in postman we should not add a content-type to the post it will automatically detect the content-type and resolve it.
