### ISSUE TITLE
Episode 5 observations

### ISSUE THREAD

**Issue by snapey** [themsaid/ergodnc#14]
Your code is using 'public' disk everywhere.  I know you said that you would move this to s3 maybe in production, but this means changing all public disk use to s3 but you may have other uses for the public disk.

I would prefer to create a new disk just for images which initially maps to local but can change to map to an S3 bucket later.

---

I find it useful to store the disk name in the images table. This allows images to migrated from one disk to another at some point in the future.

---

API should return the full URI of the image so that the consumer does not need to know where the images are being stored and can just use the URI directly.

**Comment by themsaid** [comment]
@snapey I switched to using the default disk in episode 6 so it's easier to make the switch.

---

Good point. But I don't think I'll need to migrate from one disk to another for this project

---

Good point. I've added it to the TODO list

Thanks :)
