### ISSUE TITLE
Assigning a new office approval_status is redundant

### ISSUE THREAD

**Issue by bryceandy** [themsaid/ergodnc#16]
When we created the office migration, the default `approval_status` is pending (1).  

Why do we also need to do the following in the controller when creating an office?

```
$attributes['approval_status'] = Office::APPROVAL_PENDING;
```

**NOTE**:  If we remove that line in the controller, the `JsonResource` response when creating an office does NOT contain the default pending status from the database. This will make the following assertion to fail:

```
->assertJsonPath('data.approval_status', Office::APPROVAL_PENDING)
```

**Comment by themsaid** [comment]
> Why do we also need to do the following in the controller when creating an office?

I like to keep things explicit, so it's easier for another developer to assume what's going to happen.

**Comment by bryceandy** [comment]
Understood.

> **NOTE**: If we remove that line in the controller, the `JsonResource` response when creating an office does NOT contain the default pending status from the database.

About this part, could this be a bug in the framework or it is intended?

**Comment by themsaid** [comment]
It's expected, because to read the defaults from the DB you need to send a select query after the insert query.
