### ISSUE TITLE
Date Between

### ISSUE THREAD

**Issue by kingdomac** [themsaid/ergodnc#18]
What if the reservation date range is wider than the search date range !? 
The search date range will be included in the reservation date range but the reservation will not be shown in the result. But the office in fact will be reserved and occupied in this date search range.
EX:
Search: "2021-02-01" to "2021-04-01"
Reservation: "2021-01-01" end "2021-05-01"
"2021-01-01" not between "2021-02-01" & "2021-04-01"
"2021-05-01" not between "2021-02-01" & "2021-04-01"
but ["2021-02-01" & "2021-04-01"] is inside ["2021-01-01" & "2021-05-01"]

**Comment by themsaid** [comment]
That's a good point. What would you do to include that reservation in the results?

**Comment by kingdomac** [comment]
We can add new where condition:
start_date ‹ from_date and end_date › to_date
