### ISSUE TITLE
Error: Call to a member function getAttributes() on null -Episode 2

### ISSUE THREAD

**Issue by chisumo2016** [themsaid/ergodnc#2]
Tests\Feature\OfficeControllerTest > it shows the office
  Expected response status code [200] but received 500.
  
  The following exception occurred during the request:
  
  Error: Call to a member function getAttributes() on null in /Users/os/Documents/projects/office-reservation/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php:88
  Stack trace:

Code

/**
     * @test
     */
    public function itShowsTheOffice()
    {
        $user = User::factory()->create();
        $tag = Tag::factory()->create();
        $office = Office::factory()->for($user)->create();

        $office->tags()->attach($tag);
        $office->images()->create(['path' => 'image.jpg']);

        Reservation::factory()->for($office)->create(['status' => Reservation::STATUS_ACTIVE]);
        Reservation::factory()->for($office)->create(['status' => Reservation::STATUS_CANCELLED]);

        $response = $this->get('/api/offices/'.$office->id);

        $response->assertOk()
            ->assertJsonPath('data.reservations_count', 1)
            ->assertJsonCount(1, 'data.tags')
            ->assertJsonCount(1, 'data.images')
            ->assertJsonPath('data.user.id', $user->id);
    }

Controller
 public function  show(Office $office): JsonResource
    {
        $office->loadCount(['reservations' => fn($builder) => $builder->where('status', Reservation::STATUS_ACTIVE)])
            ->load(['images', 'tags', 'user']);

       return OfficeResource::make($office);
    }

**Comment by gul-ahmad** [comment]
Everything looks fine here....
I guest you might have missed some the releations area
