### ISSUE TITLE
Create Reservation

### ISSUE THREAD

**Issue by kingdomac** [themsaid/ergodnc#23]
- Missing the validate() function on validator() helper
- Changing the key messages related to the date to "date_range" instead of "office_id"
- The diffDays return a floor result so to get the real number of days you should use (int)ceil() and floatDiffInRealDays:
_$numberOfDays = (int)ceil(Carbon::parse(request('end_date'))->endOfDay()->floatDiffInRealDays(
                Carbon::parse(request('start_date'))->startOfDay()
            ));
so now the difference between addDays(1) and addDays(40) will be 40  as you are getting the startDay of the first one and the endDate of the second one.
Note: (Change in the testing 41 to 40)

```
**Error:**
- the calculation between today and tomorrow is 1.99999 which is 1 for floor and 2 for ceil functions

- If you use only addition by one the calculation will be wrong
```

- If you want to keep the logic of a 1-day reservation not allowed remove the condition because it already exists inside the validator
when using the after:start_date for the end_date

**Comment by themsaid** [comment]
thanks. fixed that now
